spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev #开发环境
  application:
    name: example-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        refresh-enabled: true
        file-extension: yml
        data-id: ${spring.application.name}-${spring.profiles.active}
        group-id: DEFAULT_GROUP
      username: nacos
      password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example_business_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:12001         #匹配后提供服务的路由地址
          uri: lb://example-business          #匹配后提供服务的路由地址
          predicates:
            - Method=GET,POST
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        # 应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        # 默认8719端口，假如端口被占用，依次+1，直到找到未被占用端口
        port: 8719
      datasource:
        dsl:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: example-gateway-sentinel-config
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
server:
  port: 8998

logging:
  level:
    root: info
