spring:
  profiles:
    active: dev #开发环境
  application:
    name: example-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        refresh-enabled: true
        file-extension: yml
        data-id: ${spring.application.name}-${spring.profiles.active}
        group-id: DEFAULT_GROUP
      username: nacos
      password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example_business_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:12001         #匹配后提供服务的路由地址
          uri: lb://example-business          #匹配后提供服务的路由地址
          predicates:
            - Path= /demo/**
server:
  port: 8998

logging:
  level:
    root: debug
